---
name: 02 Azure Landing Zones Continuous Delivery
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      skip_what_if:
        description: 'Skip What If Check?'
        default: false
        type: boolean
      management_groups:
        description: 'Run Steps: Management Groups'
        type: boolean
        default: true
      logging_and_sentinel:
        description: 'Run Steps: Logging and Sentinel'
        type: boolean
        default: true
      policy_definitions:
        description: 'Run Steps: Policy Definitions'
        type: boolean
        default: true
      role_definitions:
        description: 'Run Steps: Role Definitions'
        type: boolean
        default: true
      policy_assignments:
        description: 'Run Steps: Policy Assignments'
        type: boolean
        default: true
      management_group_diagnostic_settings:
        description: 'Run Steps: Management Group Diagnostic Settings'
        type: boolean
        default: true
      subscription_placement:
        description: 'Run Steps: Subscription Placement'
        type: boolean
        default: true
      connectivity:
        description: 'Run Steps: Connectivity'
        type: boolean
        default: true
      destroy:
        description: '[DANGER!] Destroy? [DANGER!]'
        default: false
        type: boolean

jobs:
  plan_and_apply:
    uses: oZakari-ALZ/gh-mgmt-templates/.github/workflows/cd-template.yaml@main
    name: 'CD'
    permissions:
      id-token: write
      contents: read
    with:
      skip_what_if: ${{ fromJSON((inputs.skip_what_if != '' && inputs.skip_what_if) || 'false') }}
      destroy: ${{ fromJSON((inputs.destroy != '' && inputs.destroy) || 'false') }}
      management_groups: ${{ fromJSON((inputs.management_groups != '' && inputs.management_groups) || 'true') }}
      logging_and_sentinel_resource_group: ${{ fromJSON((inputs.logging_and_sentinel != '' && inputs.logging_and_sentinel) || 'true') }}
      logging_and_sentinel: ${{ fromJSON((inputs.logging_and_sentinel != '' && inputs.logging_and_sentinel) || 'true') }}
      custom_policy_definitions: ${{ fromJSON((inputs.policy_definitions != '' && inputs.policy_definitions) || 'true') }}
      custom_role_definitions: ${{ fromJSON((inputs.role_definitions != '' && inputs.role_definitions) || 'true') }}
      management_group_diagnostic_settings: ${{ fromJSON((inputs.management_group_diagnostic_settings != '' && inputs.management_group_diagnostic_settings) || 'true') }}
      policy_assignments: ${{ fromJSON((inputs.policy_assignments != '' && inputs.policy_assignments) || 'true') }}
      workload_specific_policy_assignments: ${{ fromJSON((inputs.policy_assignments != '' && inputs.policy_assignments) || 'true') }}
      subscription_placement: ${{ fromJSON((inputs.subscription_placement != '' && inputs.subscription_placement) || 'true') }}
      connectivity_resource_group: ${{ fromJSON((inputs.connectivity != '' && inputs.connectivity) || 'true') }}
